export const Product = [
    {
        id: 1,
        name: 'Chinese cabbage',
        price: 10,
        rating: 4.5,
        image: '/product/cabbage.svg',
        wishList: true,
        cart: true,
        description:
            'Chinese cabbage is a type of cabbage that is grown for its leaves. It is a cruciferous vegetable that is part of the Brassica family, which also includes broccoli, cauliflower, and cabbage.',
        category: 'Vegetable',
        tags: ['Chinese cabbage', 'Cruciferous', 'Brassica family', 'Vegetable'],
        quantity: 12,
        unit: 'kg',
    },
    {
        id: 2,
        name: 'fresh indianapple',
        price: 10,
        rating: 4.5,
        image: '/product/apple.svg',
        wishList: false,
        cart: false,
        description:
            'Apple is a sweet and juicy fruit that is often eaten fresh or used in cooking. It is a member of the Rosaceae family and is known for its tart and sweet taste.',
        category: 'Fruit',
        tags: ['Apple', 'Sweet', 'Juicy', 'Fruit'],
        quantity: 12,
        unit: 'kg',
    },
    {
        id: 3,
        name: 'malta',
        price: 10,
        rating: 4.5,
        image: '/product/malta.svg',
        wishList: false,
        cart: false,
        description:
            'Malta is a type of fruit that is often eaten fresh or used in cooking. It is a member of the Rosaceae family and is known for its tart and sweet taste.',
        category: 'Fruit',
        tags: ['Malta', 'Sweet', 'Juicy', 'Fruit'],
        quantity: 12,
        unit: 'kg',
    },
    {
        id: 4,
        name: 'green lettuce',
        price: 10,
        rating: 4.5,
        image: '/product/lettuce.svg',
        wishList: false,
        cart: false,
        description:
            'Lettuce is a type of leaf vegetable that is often eaten fresh or used in cooking. It is a member of the Lactuca family and is known for its crisp and crunchy texture.',
        category: 'Vegetable',
        tags: ['Lettuce', 'Crunchy', 'Vegetable', 'Lactuca family'],
        quantity: 12,
        unit: 'kg',
    },
    {
        id: 5,
        name: 'eggplant',
        price: 10,
        rating: 4.5,
        image: '/product/eggplant.svg',
        wishList: false,
        cart: false,
        description:
            'Eggplant is a type of vegetable that is often eaten fresh or used in cooking. It is a member of the Solanaceae family and is known for its purple skin and soft, spongy flesh.',
        category: 'Vegetable',
        tags: ['Eggplant', 'Purple', 'Soft', 'Vegetable', 'Solanaceae family'],
        quantity: 12,
        unit: 'kg',
    },
    {
        id: 6,
        name: 'big potatoes',
        price: 10,
        rating: 4.5,
        image: '/product/potatoes.svg',
        wishList: false,
        cart: false,
        description:
            'Potatoes are a type of vegetable that is often eaten fresh or used in cooking. They are a member of the Solanaceae family and are known for their starchy texture.',
        category: 'Vegetable',
        tags: ['Potatoes', 'Starchy', 'Vegetable', 'Solanaceae family'],
        quantity: 12,
        unit: 'kg',
    },
    {
        id: 7,
        name: 'corn',
        price: 10,
        rating: 4.5,
        image: '/product/corn.svg',
        wishList: false,
        cart: false,
        description:
            'Corn is a type of grain that is often eaten fresh or used in cooking. It is a member of the Poaceae family and is known for its sweet and crunchy texture.',
        category: 'Grain',
        tags: ['Corn', 'Sweet', 'Crunchy', 'Grain', 'Poaceae family'],
        quantity: 12,
        unit: 'kg',
    },
    {
        id: 8,
        name: ' fresh cauliflower',
        price: 10,
        rating: 4.5,
        image: '/product/cauliflower.svg',
        wishList: false,
        cart: false,
        description:
            'Cauliflower is a type of vegetable that is often eaten fresh or used in cooking. It is a member of the Brassica family and is known for its white, fluffy texture.',
        category: 'Vegetable',
        tags: ['Cauliflower', 'White', 'Fluffy', 'Vegetable', 'Brassica family'],
        quantity: 12,
        unit: 'kg',
    },
    {
        id: 9,
        name: 'green capsicum',
        price: 10,
        rating: 4.5,
        image: '/product/capsicum.svg',
        wishList: false,
        cart: false,
        description:
            'Green capsicum is a type of vegetable that is often eaten fresh or used in cooking. It is a member of the Solanaceae family and is known for its green color and mild taste.',
        category: 'Vegetable',
        tags: ['Green capsicum', 'Green', 'Mild', 'Vegetable', 'Solanaceae family'],
        quantity: 12,
        unit: 'kg',
    },
    {
        id: 10,
        name: 'green chilli',
        price: 10,
        rating: 4.5,
        image: '/product/chili.svg',
        wishList: false,
        cart: false,
        description:
            'Green chilli is a type of vegetable that is often eaten fresh or used in cooking. It is a member of the Solanaceae family and is known for its green color and mild taste.',
        category: 'Vegetable',
        tags: ['Green chilli', 'Green', 'Mild', 'Vegetable', 'Solanaceae family'],
        quantity: 12,
        unit: 'kg',
    },
]
