export const testimonial = [
    {
        id: 1,
        title: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos.',
        rating: 4,
        avatar: '/users/john.png',
        name: 'John Doe',
        role: 'Customer',
    },
    {
        id: 2,
        title: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos.',
        rating: 4,
        avatar: '/users/patrick.png',
        name: 'Patrick Muhoozi',
        role: 'Customer',
    },
    {
        id: 3,
        title: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos.',
        rating: 4,
        avatar: '/users/jane.png',
        name: 'Jane Doe',
        role: 'Customer',
    },
    {
        id: 4,
        title: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos.',
        rating: 4,
        avatar: '/users/john.png',
        name: 'John Doe',
        role: 'Customer',
    },
    {
        id: 5,
        title: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quos.',
        rating: 4,
        avatar: '/users/patrick.png',
        name: 'Patrick Muhoozi',
        role: 'Customer',
    },
]
